## Analysis of Missingness
# A lot of the write up on this script suggests maybe that a markdown/report could be in the works?

library(tidyverse)
library(mice)
library(naniar)
library(UpSetR)
library(ggplot2)
library(VIM)
library(reshape2)

# Graphing patterns of missingness
bench$chur_tidy %>% 
  as_shadow_upset() %>%
  upset(nsets = 7)

# An additional visual representation of missingness
ggplot_missing <- function(x){
  x %>% is.na %>%
    melt %>%
    ggplot(data = .,
           aes(x = Var2, 
               y = Var1)) +
    geom_raster(aes(fill = value))+
    scale_fill_grey(name = "",
                    labels = c("Present", "Missing"))+
    theme_minimal()+
    theme(axis.text.x = element_text(angle=45, vjust = 0.7)) +
    labs(x = "Variables in Dataset",
         y = "Rows / Observations")
}

ggplot_missing(bench$chur_tidy) ## Map of missingness

mean(complete.cases(bench$chur_tidy)) # Percentage of complete surveys
sum(complete.cases(bench$chur_tidy)) # Total number of complete cases
sum(is.na(bench$chur_tidy))/prod(dim(bench$chur_tidy)) # Total percent of missingess overall
sapply(bench$chur_tidy, function(x) sum(is.na(x))) # Sum of each individual item's missingness
sapply(bench$chur_tidy, function(x) mean(is.na(x))) %>%
  round(digits = 2) # Percentage of each individual item's missingness

bench$miss <- # Creating a df for purposes of analysis of missingness and imputation
  bench$chur_tidy %>% # Should probably hang this on this list.
  select(ID, city, num_nights, burner_v2:whatfest) %>%
  mutate(whatfest = as.numeric(factor(whatfest, labels = c('1', '2', '3'))))

mcar_test(bench$miss) #MCAR Test for Analysis of Missingess

  # Little's MCAR test
  ## First LittleMCAR test failed indicating that data was not MCAR suggesting that imputation could not be 
  ## performed.  Individuals responses were analyzed to see if patterns of missingness in the data could be inferred.
  
  ## sure enough...
  
  ## Respondent 46: missing data on whatkind and farfest having answered 1 for keenfest.  Very possible that 
  ## that these were left blank on account of the individual not being keen on a Chur Festival at all and them
  ## believing that answering these questions did not apply.

bench$miss$whatfest[46] <- 1
bench$miss$farfest[46] <- 1

## Once these new items were added to the dataset, a second Little MCAR test was performed, whereby non-significant
## p value was obtained, indicating that data was MCAR and that we could proceded with missing imputation. 
## Although the values for Whatfest and Farfest were low, it does not necessarily follow that the keenfest score for 
## this individual would be low as well (i.e. there is a high likelyhood of randomness pertaining to the missingness of 
## this item as indicated by a non-significant Little's MCAR test result).  

mcar_test(bench$miss_test) # Second application of Little's MCAR test after manual imputations of missing values.

# Imputation of Missing Data using mice package.
bench$temp$mi.temp <- 
  mice(bench$miss, m = 5, maxit = 50, meth = 'pmm', seed = 500)
summary(bench$temp$mi.temp)

bench$temp$mi.temp$imp$keenfest #eyeballing imputed data as generated by mice

bench$miss <- as.tibble(complete(bench$temp$mi.temp, 1)) # Chosen as a conservative value, which is also consistent with outputs of other imputation methods (e.g. Bayes)

bench$chur_clean <- #Merging OE questions with the rest of the dataset
  left_join(bench$miss, select(bench$chur_tidy, ID, welly_TF, nights, love:fdback), by = "ID") %>%
  select(ID, city, welly_TF, nights, num_nights, nxtyear, burner_v2,  gtp:whatfest, love:fdback)
